title: Tucker Lein
email: self@tuckerle.in
description: > 
  Tucker Lein's portfolio page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tlein
linkedin_username: tuckerlein

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - serve.py
  - tags
  - index.pug
  - contact.pug
  - resume.pug
  - portfolio.pug
